# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: AlignTechnology,Inc.InvisalignOutcomeSimulator
PackageVersion: 4.2.1.75
InstallerType: exe
InstallerSwitches:
  Silent: /s
Installers:
- Architecture: x64
  InstallerUrl: https://storagy-akamai-production-us.s3.amazonaws.com/Invisalign_Outcome_Simulator_4.2.1.75.exe
  InstallerSha256: EE0C80DE8124B5BF756097BA0CD62E08E0656AC107C9D37069DCB5019A3FA45F
ManifestType: installer
ManifestVersion: 1.5.0
